# Generated by Django 4.1.1 on 2022-10-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_title', models.CharField(max_length=40, verbose_name='Название')),
                ('favourite_description', models.TextField(verbose_name='Описание')),
                ('favourite_sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время ')),
            ],
        ),
    ]
